---
title: "Results"
author: "Epiforecasts"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, 
                      warning = FALSE, message = FALSE,
                      root.dir = here::here())
options(scipen = 1, digits = 2)
library(here)
library(forecast.vocs)
library(purrr)
library(dplyr)
library(scoringutils)
library(loo)
library(ggplot2)
library(knitr)
aim <- "transmission"
voc <- ifelse(aim == "transmission", "Omicron", "any-SGT-result")
non_voc <- ifelse(aim == "transmission", "Delta", "no-SGT-result")

# get data and parameters without rebuilding model
run_model <- FALSE
source(here(aim, paste0("model-", aim, ".R")))

# both models are fit to raw or smooth (7-day MA) data. Select which to show for results
data_types <- c("data-raw", "data-smooth")
data_type <- data_types[1] # use fit to raw data
data_type_clean <- gsub("data-", "", data_type)
obs <- as.data.table(datasets[[data_type]])

# get model outputs
forecast_fits <- readRDS(here(aim, data_type, "fit", "forecast-fits.rds"))[[variant_relationships]]
forecasts <- readRDS(here(aim, data_type, 
                          "fit", "forecasts.rds"))[[variant_relationships]]

# Plot transmission advantage
advantage <- forecasts %>%
  filter(value_type == "model" & variable == "avg_voc_advantage") %>%
  select(variant_relationship, variable, clean_name, exponentiated:ess_bulk)
```
- `r round(mean(obs$share_voc, na.rm=T)*100)`% cases were VoC 
- We used daily, `r data_type_clean` data 

- We found a median advantage for `r voc` cases of `r exp(advantage$median)` (95% credible interval `r exp(advantage$q5)` - `r exp(advantage$q95)`), scaled against `r non_voc` cases

```{r}
forecast.vocs::plot_posterior()
```
